import Head from "next/head";
import Navbar from "../../Components/Shared/Navbar/Navbar";
import M_CategoryLists from "./../../Components/Men/CategoryLists/M_CategoryLists";
import M_PriceRange from "./../../Components/Men/PriceRange/M_PriceRange";
import M_Size from "./../../Components/Men/Size/M_Size";
import M_Products from "./../../Components/Men/M_Products/M_Products";

const men = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <section className="container mx-auto flex gap-2">
          <div className="w-1/5">
            <M_CategoryLists />
            <M_PriceRange />
            <M_Size />
          </div>
          <div className="w-4/5 ">
            <M_Products />
          </div>
        </section>
      </main>
    </>
  );
};

export default men;
