import Head from "next/head";
import Navbar from "./../../Components/Shared/Navbar/Navbar";
import C_CategoryLists from './../../Components/Children/CategoryLists/C_CategoryLists';
import C_PriceRange from "../../Components/Children/PriceRange/C_PriceRange";
import C_Size from './../../Components/Children/Size/C_Size';
import C_Products from './../../Components/Children/C_Products/C_Products';

const children = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <section className="container mx-auto flex gap-2">
          <div className="w-1/5">
            <C_CategoryLists />
            <C_PriceRange />
            <C_Size />
          </div>
          <div className="w-4/5 ">
            <C_Products />
          </div>
        </section>
      </main>
    </>
  );
};

export default children;
