import React from "react";
import Footer from "../Components/Shared/Footer/Footer";
import Navbar from "../Components/Shared/Navbar/Navbar";
import Head from "next/head";

const Layouts = ({ title, children }) => {
  return (
    <>
      <Head>
        <title>{title ? title+ " | E-commerce-shop" : "E-commerce-shop"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>{children}</main>
      {!title === "login" && <Footer />}
      {!title === "Register" && <Footer /> }
      {title === "Home" && <Footer /> }
    </>
  );
};

export default Layouts;
