import Head from "next/head";
import Image from "next/image";
import { Poppins } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Navbar from "./../Components/Shared/Navbar/Navbar";
import Header from "../Components/Home/Header/Header";
import OfferCategories from "../Components/Home/OfferCategories/OfferCategories";
import ShopByCategories from "../Components/Home/ShopByCategories/ShopByCategories";
import Banner from "../Components/Home/Banner/Banner";
import M_ShoesCollection from "../Components/Home/M_ShoesCollection/M_ShoesCollection";
import W_ShoesCollection from "../Components/Home/W_ShoesCollection/W_ShoesCollection";
import C_ShoesCollection from "./../Components/Home/C_ShoesCollection/C_ShoesCollection";
import GiftCollection from "../Components/Home/GiftCollection/GiftCollection";
import DiscountBanner from "../Components/Home/DiscountBanner/DiscountBanner";
import Footer from "../Components/Shared/Footer/Footer";

const poppins = Poppins({ weight: "400" }, { subsets: "poppins" });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main className={poppins.className}>
        <Header />
        <OfferCategories />
        <ShopByCategories />
        <Banner />
        <M_ShoesCollection />
        <W_ShoesCollection />
        <C_ShoesCollection />
        <DiscountBanner />
        <GiftCollection />
      </main>
      <Footer />
    </>
  );
}
