import Head from "next/head";
import Navbar from "./../../Components/Shared/Navbar/Navbar";
import CategoryLists from "../../Components/Women/CategoryLists/CategoryLists.js";
import PriceRange from "../../Components/Women/PriceRange/PriceRange";
import Size from "../../Components/Women/Size/Size";
import W_Products from "../../Components/Women/W_Products/W_Products";

const women = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <section className="container mx-auto flex gap-2">
          <div className="w-1/5">
            <CategoryLists />
            <PriceRange />
            <Size />
          </div>
          <div className="w-4/5 ">
            <W_Products />
          </div>
        </section>
      </main>
    </>
  );
};

export default women;
